base:
 bin_location: '/group/ctbrowngrp2/amhorst/2025-pigparadigm/results/MAGs/all_genomes'
 extension: 'fasta'

rename:
 keep_original_ident: False
 new_prefix: AtH                # ignored if keep_original_names is True


