base:
 bin_location: '/home/ctbrown/scratch3/2025-other-pig-bins/wur_mattia_semibin2_cobinning_drep-95-99'
 extension: 'fa.gz'
 outputs: 'outputs.semibin2'

rename:
 keep_original_ident: False
 new_prefix: NNF_SEMIBIN2                # ignored if keep_original_names is True
